[package]
name = "moth"
version = "0.1.12"
edition = "2024"

[workspace]
members = [".", "xtask"]
resolver = "2"

[features]
# These add println! macros for debugging and info when compiling
timers = []
detailed_timers = ["timers"]
benchmark_counters = []
show_tokens = []
show_headers = []
show_ast = []
show_eval = []
show_hir = []
show_codegen = []
show_borrow_checker = []
checked_blocks = []
async_blocks = []

[[bin]]
name = "moth"
path = "src/main.rs"

[dependencies]
rayon = "1.12"
rustc-hash = "2.1.1"
saying = "0.1.8"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
toml = "1.1.2"
wasm-encoder = "0.247.0"
wasmparser = "0.247.0"
notify = "8.2.0"
ryu = "1.0.23"

# For future release builds:
# oxc_minifier = "0.115.0"

pulldown-cmark = { version = "0.13.4", default-features = false, features = ["html"] }

[dev-dependencies]
tempfile = "3"

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true

[profile.profiling]
inherits = "release"
debug = true
strip = false
lto = "thin"
codegen-units = 1
panic = "abort"

[profile.dev.package."*"]
opt-level = 3  # Optimize dependencies in dev
