//! Zero-cost timer erasure gate, and the timer subsystem's source rules.
//!
//! WHAT: builds the `moth` release binary without any timer-related feature
//!      and proves that timer-only implementation markers are absent from the
//!      produced bytes. It also defines the timer source rules — runtime `cfg!`
//!      checks, direct calls into the enabled implementation outside the
//!      facade, direct wall clocks, obsolete macro and metric names, unguarded
//!      timer-only fields, and no-op timer closure wrappers, because a disabled
//!      frontend timer expansion must be the production expression itself.
//! WHY:  the plan's primary invariant is that a compiler built without
//!       `timers` performs no timer-system runtime work. Source-level erasure
//!       tests prove macro semantics; this gate proves the compiled artifact
//!       contains none of the timer-only strings that a live implementation
//!       would retain.
//!
//! The rules defined here are applied by `source_audit`, which owns the single
//! walk of the tree and reports typed findings. This module owns what the rules
//! are, not when they run: a second walk would be a second place for a rule to
//! be silently skipped.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

/// Timer-only marker strings that must never appear in a no-timer binary.
///
/// `MOTH_BENCH status` is deliberately absent: it is the separate
/// benchmark-status contract and remains valid without `timers`.
const TIMER_ONLY_MARKERS: &[&str] = &[
    "MOTH_TIMERS",
    "MOTH_BENCH timing-schema",
    "MOTH_BENCH timing",
    "Timing summary:",
    "Build timings",
    "Compilation boundaries",
    "build.boundary.inventory",
    "frontend.module.semantic_total",
    "frontend.public_interface",
    "frontend.generated_functions",
    "frontend.borrow.generated",
    // Provisional raw timing names are also forbidden from a no-timer binary.
    "headers_ms",
    "ast_ms",
    "hir_ms",
    "borrow_ms",
    "ast_function_body_parse_ms",
    "ast_start_body_parse_ms",
    "ast_build_environment_ms",
    "ast_emit_nodes_ms",
    "ast_finalize_ms",
    "command.dev.build_and_write",
    "command.dev.cycle",
];

const OBSOLETE_TIMER_MACRO_NAMES: &[&str] = &["timed_frontend_stage", "timed_frontend_substep"];

const OBSOLETE_RAW_TIMING_NAMES: &[&str] = &[
    "headers_ms",
    "ast_ms",
    "hir_ms",
    "borrow_ms",
    "ast_function_body_parse_ms",
    "ast_start_body_parse_ms",
    "ast_build_environment_ms",
    "ast_emit_nodes_ms",
    "ast_finalize_ms",
    "backend.js.lower_hir",
    "backend.js.lower_linked_hir",
];

const TIMER_ONLY_FIELD_MARKERS: &[&str] = &[
    "timing_context:",
    "timing_metric_family:",
    "timing_boundary:",
    "timing_module_key:",
    "timing_snapshot:",
];

/// Run the complete erasure gate.
pub fn run_timers_erasure_check() -> Result<(), String> {
    let workspace_root = workspace_root()?;

    build_no_timer_release_binary(&workspace_root)?;

    let binary_path = no_timer_release_binary_path(&workspace_root);
    let binary_bytes = fs::read(&binary_path).map_err(|error| {
        format!(
            "failed to read the no-timer release binary '{}': {error}",
            binary_path.display()
        )
    })?;

    let mut present_markers: Vec<String> = find_present_markers(&binary_bytes, TIMER_ONLY_MARKERS)
        .into_iter()
        .map(str::to_owned)
        .collect();
    present_markers.extend(find_present_schema_metric_markers(&binary_bytes));
    if !present_markers.is_empty() {
        return Err(format!(
            "no-timer release binary contains timer-only markers: {}",
            present_markers.join(", ")
        ));
    }

    println!(
        "timers-erasure-check: no-timer binary clean ({} bytes); the timer source rules run in \
         `just source-audit`",
        binary_bytes.len()
    );
    Ok(())
}

/// Return the markers present in the given bytes, in declaration order.
fn find_present_markers<'a>(bytes: &[u8], markers: &'a [&str]) -> Vec<&'a str> {
    markers
        .iter()
        .copied()
        .filter(|marker| {
            bytes
                .windows(marker.len())
                .any(|window| window == marker.as_bytes())
        })
        .collect()
}

/// Find every stable metric name in the timing schema inventory.
///
/// The inventory is generated by the typed schema registry and exposed through
/// the benchmark API, so this binary audit cannot silently drift to a hand-
/// maintained subset when a metric is added or renamed. The names are checked
/// independently from the `MOTH_BENCH timing ` prefix: a leaked registry can
/// retain a raw metric name without retaining a complete formatted output line.
fn find_present_schema_metric_markers(bytes: &[u8]) -> Vec<String> {
    moth::benchmarking::TIMING_SCHEMA_METRIC_NAMES
        .iter()
        .filter(|name| {
            bytes
                .windows(name.len())
                .any(|window| window == name.as_bytes())
        })
        .map(|name| (*name).to_owned())
        .collect()
}

/// Build the `moth` binary with no default features in an isolated target dir.
fn build_no_timer_release_binary(workspace_root: &Path) -> Result<(), String> {
    let target_dir = workspace_root.join("target").join("timers-erasure-check");

    let status = Command::new("cargo")
        .arg("build")
        .arg("--release")
        .arg("--no-default-features")
        .arg("--bin")
        .arg("moth")
        .env("CARGO_TARGET_DIR", &target_dir)
        .current_dir(workspace_root)
        .status()
        .map_err(|error| format!("failed to launch the no-timer release build: {error}"))?;

    if !status.success() {
        return Err("the no-timer release build failed".to_string());
    }

    Ok(())
}

/// Locate the built no-timer release binary.
fn no_timer_release_binary_path(workspace_root: &Path) -> PathBuf {
    let binary_name = if cfg!(windows) { "moth.exe" } else { "moth" };
    workspace_root
        .join("target")
        .join("timers-erasure-check")
        .join("release")
        .join(binary_name)
}

/// Run the timer source rules against one Rust source fragment.
///
/// `relative` is the workspace-relative path with `/` separators, which the allowlists match
/// against. The timing facade is exempt from the rules that exist to keep callers off the enabled
/// implementation: the facade is the thing they must go through.
///
/// Applied by `source_audit`, which owns the walk. Separated from any walk so each rule has
/// focused coverage against fixture text rather than against whatever the tree happens to hold.
pub(crate) fn audit_timer_source_fragment(relative: &str, content: &str) -> Vec<String> {
    let is_facade_path = relative == "src/timing.rs" || relative.starts_with("src/timing/");
    let mut failures = Vec::new();

    if content.contains("cfg!(feature = \"timers\")") {
        failures.push("uses runtime cfg! check; use #[cfg] macro definitions instead".to_owned());
    }

    if !is_facade_path
        && (content.contains("timing::enabled::") || content.contains("timing::collector::"))
    {
        failures
            .push("calls enabled timer implementation directly; use the facade macros".to_owned());
    }

    if !is_facade_path
        && content.contains("Instant::now()")
        && !is_allowed_wall_clock_source(relative)
    {
        failures.push("creates a direct timer clock outside timing internals; use the timing facade or an explicitly allowed wall-clock owner".to_owned());
    }

    if content.contains("$stage()") {
        failures.push("timed_frontend_stage! expands through a closure call; expand the production expression directly".to_owned());
    }

    if content.contains("$substep()") || content.contains("substep()") {
        failures.push("timed_frontend_substep! expands through a closure call; expand the production expression directly".to_owned());
    }

    if content.contains("fn timed_frontend_substep<") || content.contains("timed_frontend_substep(")
    {
        failures.push(
            "timed_frontend_substep must be a direct-expression macro, not a function wrapper"
                .to_owned(),
        );
    }

    for macro_name in OBSOLETE_TIMER_MACRO_NAMES {
        if content.contains(macro_name) {
            failures.push(format!(
                "obsolete timer macro name '{macro_name}' remains; use the typed facade"
            ));
        }
    }

    if !is_allowed_legacy_metric_source(relative) {
        for metric_name in OBSOLETE_RAW_TIMING_NAMES {
            if content.contains(metric_name) {
                failures.push(format!(
                    "obsolete raw timing metric '{metric_name}' remains outside schema tests or history adapters"
                ));
            }
        }
    }

    if !is_allowed_schema_metric_source(relative) {
        for metric_name in moth::benchmarking::TIMING_SCHEMA_METRIC_NAMES {
            let quoted_metric_name = format!("\"{metric_name}\"");
            if content.contains(&quoted_metric_name) {
                failures.push(format!(
                    "current timing schema metric '{metric_name}' is hard-coded outside the schema owner; use the typed registry"
                ));
            }
        }
    }

    if !is_facade_path && has_unguarded_timer_only_field(content) {
        failures
            .push("timer-only field or parameter lacks #[cfg(feature = \"timers\")]".to_owned());
    }

    failures
}

fn is_allowed_legacy_metric_source(relative: &str) -> bool {
    is_test_source(relative) || relative.contains("/history")
}

/// Current metric names have one production owner. Tests may mention literal
/// names to exercise the compatibility boundary, but production code must
/// consume the typed schema descriptor instead.
fn is_allowed_schema_metric_source(relative: &str) -> bool {
    relative == "src/timing/enabled/schema.rs" || is_test_source(relative)
}

fn is_test_source(relative: &str) -> bool {
    relative.contains("/tests/")
        || relative.ends_with("/tests.rs")
        || relative.ends_with("_tests.rs")
}

fn has_unguarded_timer_only_field(content: &str) -> bool {
    let lines: Vec<&str> = content.lines().collect();
    lines.iter().enumerate().any(|(index, line)| {
        let contains_timer_field = TIMER_ONLY_FIELD_MARKERS
            .iter()
            .any(|marker| line.contains(marker));
        if !contains_timer_field {
            return false;
        }

        let line_guarded = line.contains("#[cfg(feature = \"timers\")]");
        let previous_guarded = lines
            .get(index.saturating_sub(1))
            .is_some_and(|previous| previous.contains("#[cfg(feature = \"timers\")]"));

        contains_timer_field && !(line_guarded || previous_guarded)
    })
}

/// Return whether direct `Instant` use belongs to an explicitly non-timer
/// wall-clock owner. These clocks exist for user-facing elapsed messages,
/// integration-test reporting, subprocess deadlines, cross-thread test
/// deadlines, or the in-process benchmark harness; they do not feed the timing
/// collector or its schema.
fn is_allowed_wall_clock_source(relative: &str) -> bool {
    matches!(
        relative,
        "src/benchmarking/frontend.rs"
            | "src/compiler_tests/integration_test_runner/assertions/node_harness.rs"
            | "src/compiler_tests/integration_test_runner/runner.rs"
            | "src/projects/cli.rs"
            | "src/projects/check.rs"
            | "src/projects/dev_server/build_loop.rs"
            | "src/projects/dev_server/tests/sse_tests.rs"
            | "xtask/src/process_runner.rs"
            | "xtask/src/profile/runner.rs"
    )
}

fn workspace_root() -> Result<PathBuf, String> {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .map(Path::to_path_buf)
        .ok_or_else(|| "xtask manifest has no parent directory".to_string())
}

#[cfg(test)]
mod tests {
    use super::{
        audit_timer_source_fragment, find_present_markers, find_present_schema_metric_markers,
    };

    #[test]
    fn finds_present_markers_in_declaration_order() {
        let bytes = b"prefix MOTH_BENCH timing suffix MOTH_TIMERS";
        let markers = &["MOTH_TIMERS", "MOTH_BENCH timing", "Timing summary:"];

        assert_eq!(
            find_present_markers(bytes, markers),
            vec!["MOTH_TIMERS", "MOTH_BENCH timing"]
        );
    }

    #[test]
    fn rejects_none_when_markers_are_absent() {
        let bytes = b"MOTH_BENCH status errors=0 warnings=0";
        let markers = &["MOTH_TIMERS", "MOTH_BENCH timing", "Timing summary:"];

        assert!(find_present_markers(bytes, markers).is_empty());
    }

    #[test]
    fn rejects_closure_wrapper_expansion_in_frontend_stage_macro() {
        let failures = audit_timer_source_fragment(
            "src/timing.rs",
            "macro_rules! timed_frontend_stage {\n  ($stage:expr) => {{ $stage() }};\n}",
        );

        assert!(
            failures
                .iter()
                .any(|failure| failure.contains("closure call")),
            "expected a closure-wrapper failure, got: {failures:?}"
        );
    }

    #[test]
    fn rejects_function_wrapper_form_of_frontend_substep() {
        let failures = audit_timer_source_fragment(
            "src/build_system/create_project_modules/module_preparation.rs",
            "fn timed_frontend_substep<T>(_m: &'static str, _l: &str, s: impl FnOnce() -> T) -> T {\n  s()\n}",
        );

        assert!(
            failures
                .iter()
                .any(|failure| failure.contains("direct-expression macro")),
            "expected a function-wrapper failure, got: {failures:?}"
        );
    }

    #[test]
    fn accepts_direct_expression_macro_bodies() {
        let failures = audit_timer_source_fragment(
            "src/timing.rs",
            "macro_rules! direct_stage {\n  ($stage:expr) => {{ $stage }};\n}\nmacro_rules! direct_substep {\n  ($substep:expr) => {{ $substep }};\n}",
        );

        assert!(failures.is_empty(), "unexpected failures: {failures:?}");
    }

    #[test]
    fn accepts_timing_scope_attributed_opt_macro_usage() {
        // The _opt macro variant accepts Option<TimingMetric> and is a valid
        // facade macro. It must not be flagged as an obsolete timer macro or
        // a closure-wrapper timer.
        let failures = audit_timer_source_fragment(
            "src/compiler_frontend/ast/module_ast/environment/type_resolution.rs",
            "timing_scope_attributed_opt!(\n    self.context.timing_metric_family.constant_header_resolution(),\n    self.context.timing_context\n);\n",
        );

        assert!(failures.is_empty(), "unexpected failures: {failures:?}");
    }

    #[test]
    fn accepts_timed_stage_attributed_opt_macro_usage() {
        // The _opt macro variant accepts Option<TimingMetric> and evaluates the
        // expression directly when the metric is None. It must not be flagged.
        let failures = audit_timer_source_fragment(
            "src/compiler_frontend/ast/module_ast/emission/emitter.rs",
            "let result = timed_stage_attributed_opt!(\n    self.context.timing_metric_family.const_template_parse(),\n    self.context.timing_context,\n    parse_const_template(header)\n);\n",
        );

        assert!(failures.is_empty(), "unexpected failures: {failures:?}");
    }

    #[test]
    fn rejects_direct_timer_clock_outside_allowed_owner() {
        let failures = audit_timer_source_fragment(
            "src/compiler_frontend/example.rs",
            "let start = Instant::now();",
        );

        assert!(
            failures
                .iter()
                .any(|failure| failure.contains("direct timer clock")),
            "expected a direct-clock failure, got: {failures:?}"
        );
    }

    #[test]
    fn accepts_explicit_user_visible_wall_clock_owner() {
        let failures =
            audit_timer_source_fragment("src/projects/check.rs", "let start = Instant::now();");

        assert!(failures.is_empty(), "unexpected failures: {failures:?}");
    }

    #[test]
    fn rejects_obsolete_timer_macro_names() {
        let failures = audit_timer_source_fragment(
            "src/build_system/example.rs",
            "macro_rules! timed_frontend_stage { ($stage:expr) => {{ $stage }}; }",
        );

        assert!(
            failures
                .iter()
                .any(|failure| failure.contains("obsolete timer macro name")),
            "expected obsolete macro failure, got: {failures:?}"
        );
    }

    #[test]
    fn rejects_obsolete_raw_metric_literals() {
        let failures = audit_timer_source_fragment(
            "src/build_system/example.rs",
            "const METRIC: &str = \"ast_ms\";",
        );

        assert!(
            failures
                .iter()
                .any(|failure| failure.contains("obsolete raw timing metric")),
            "expected obsolete metric failure, got: {failures:?}"
        );
    }

    #[test]
    fn accepts_legacy_metric_literal_in_schema_test() {
        let failures = audit_timer_source_fragment(
            "src/timing/tests/schema_tests.rs",
            "const LEGACY_METRIC: &str = \"ast_ms\";",
        );

        assert!(failures.is_empty(), "unexpected failures: {failures:?}");
    }

    #[test]
    fn rejects_unguarded_timer_only_fields() {
        let failures = audit_timer_source_fragment(
            "src/build_system/example.rs",
            "struct Context {\n  timing_context: Option<TimingContext>,\n}",
        );

        assert!(
            failures
                .iter()
                .any(|failure| failure.contains("timer-only field")),
            "expected timer-only field failure, got: {failures:?}"
        );
    }

    #[test]
    fn accepts_cfg_guarded_timer_only_fields() {
        let failures = audit_timer_source_fragment(
            "src/build_system/example.rs",
            "struct Context {\n  #[cfg(feature = \"timers\")]\n  timing_context: Option<TimingContext>,\n}",
        );

        assert!(failures.is_empty(), "unexpected failures: {failures:?}");
    }

    #[test]
    fn rejects_a_raw_current_metric_name_from_the_schema_inventory() {
        let metric_name = moth::benchmarking::TIMING_SCHEMA_METRIC_NAMES
            .first()
            .expect("timing schema should contain one metric");

        assert_eq!(
            find_present_schema_metric_markers(metric_name.as_bytes()),
            vec![(*metric_name).to_owned()]
        );
    }

    #[test]
    fn rejects_a_current_metric_literal_outside_the_schema_owner() {
        let metric_name = moth::benchmarking::TIMING_SCHEMA_METRIC_NAMES
            .first()
            .expect("timing schema should contain one metric");
        let source = format!("const METRIC: &str = \"{metric_name}\";");

        let failures = audit_timer_source_fragment("xtask/src/bench_report.rs", &source);

        assert!(
            failures
                .iter()
                .any(|failure| failure.contains("hard-coded outside the schema owner")),
            "expected current metric literal failure, got: {failures:?}"
        );
    }

    #[test]
    fn accepts_current_metric_literals_in_the_schema_owner() {
        let metric_name = moth::benchmarking::TIMING_SCHEMA_METRIC_NAMES
            .first()
            .expect("timing schema should contain one metric");
        let source = format!("const METRIC: &str = \"{metric_name}\";");

        let failures = audit_timer_source_fragment("src/timing/enabled/schema.rs", &source);

        assert!(failures.is_empty(), "unexpected failures: {failures:?}");
    }

    #[test]
    fn accepts_current_metric_literals_in_tests() {
        let metric_name = moth::benchmarking::TIMING_SCHEMA_METRIC_NAMES
            .first()
            .expect("timing schema should contain one metric");
        let source = format!("const METRIC: &str = \"{metric_name}\";");

        let failures =
            audit_timer_source_fragment("src/build_system/tests/timing_tests.rs", &source);

        assert!(failures.is_empty(), "unexpected failures: {failures:?}");
    }

    #[test]
    fn rejects_current_metric_literals_in_production_history_adapters() {
        let metric_name = moth::benchmarking::TIMING_SCHEMA_METRIC_NAMES
            .first()
            .expect("timing schema should contain one metric");
        let source = format!("const METRIC: &str = \"{metric_name}\";");
        let failures = audit_timer_source_fragment("xtask/src/bench_history.rs", &source);

        assert!(
            failures
                .iter()
                .any(|failure| failure.contains("hard-coded outside the schema owner")),
            "expected production history metric literal failure, got: {failures:?}"
        );
    }
}
